spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/jebesme
    username: jebesme
    password: jebesme
    driver-class-name: org.postgresql.Driver
server:
  port: 8081