DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS SENTENCES
(
    id             INT     NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CROATIAN_VALUE VARCHAR NOT NULL,
    ENGLISH_VALUE  VARCHAR NOT NULL,
    IS_ALLOWED     BOOLEAN NOT NULL
);